"""Executable reasoning reference runtime / 可执行推理参考运行时。

This package exposes a deterministic reference kernel and JSON Schema-backed
artifact guards for the reasoning execution protocol. It records externally
verifiable artifacts; it never asks for or persists private chain-of-thought.
/ 本包提供确定性推理协议参考内核和基于 JSON Schema 的制品闸门。它只记录
外部可核验产物，绝不请求或持久化私密思维过程。
"""

from .reasoning_artifacts import (
    ArtifactValidationError,
    artifact_fingerprint,
    build_artifact,
    evidence_sufficiency_failures,
    validate_artifact_hash,
    validate_reasoning_contract,
    validate_reasoning_event,
    validate_reasoning_result,
    validate_schema,
    validate_workflow_route_envelope,
    validate_workflow_route_revision,
)

from .reasoning_runtime import (
    ALLOWED_TRANSITIONS,
    BudgetExceededError,
    BudgetLedger,
    BudgetLimits,
    BudgetSnapshot,
    BudgetUsage,
    CandidateRequiredError,
    DuplicateEventConflictError,
    EventSchemaViolationError,
    EventStore,
    EventStorePersistenceError,
    FeedbackAuthorizationError,
    FeedbackBlockError,
    IllegalTransitionError,
    JsonlEventStore,
    NoProgressLimitError,
    PrivateReasoningCaptureError,
    RUNTIME_SUPPORTED_STOP_TYPES,
    ReasoningEngine,
    ReasoningEvent,
    ReasoningRuntimeError,
    ReplaySnapshot,
    RiskLevel,
    RunSnapshot,
    StepStartRecord,
    StepRecord,
    ToolAuthorizationError,
    ValidationGateError,
    ValidationRecord,
    ValidationStatus,
    ValidatorSpec,
    WorkflowState,
    candidate_binding_for,
    candidate_fingerprint,
    content_fingerprint,
    validate_runtime_contract_capabilities,
)

from .reasoning_chain_factory import (
    ChainFactoryError,
    ChainPlanDriftError,
    ChainPlanSession,
    ChainPlanStateError,
    ChainStepOutcome,
    ReasoningChainFactory,
    validate_chain_blueprint,
    validate_chain_plan,
)
from .reasoning_parallel_factory import (
    ParallelBranchOutcome,
    ParallelFactoryError,
    ParallelFinalizationOutcome,
    ParallelPlanDriftError,
    ParallelPlanSession,
    ParallelPlanStateError,
    ParallelSynthesisOutcome,
    ReasoningParallelFactory,
    validate_parallel_blueprint,
    validate_parallel_plan,
)
from .reasoning_parallel_scheduler import (
    ParallelDeadlineOutcome,
    ParallelPathLease,
    ParallelPathScheduler,
)
from .reasoning_event_sqlite_store import (
    SQLITE_EVENT_SCHEMA_VERSION,
    SqliteEventStore,
)
from .reasoning_event_postgres_store import (
    POSTGRES_EVENT_SCHEMA_VERSION,
    PostgresEventStore,
)
from .reasoning_parallel_outbox import (
    SQLITE_PARALLEL_OUTBOX_SCHEMA_VERSION,
    ParallelDispatchAcquisition,
    ParallelDispatchClaimError,
    ParallelDispatchCompletion,
    ParallelDispatchConflictError,
    ParallelDispatchCoordinator,
    ParallelDispatchError,
    ParallelDispatchOutbox,
    ParallelWorkDispatch,
    SqliteParallelDispatchOutbox,
)
from .reasoning_parallel_postgres_outbox import (
    POSTGRES_PARALLEL_OUTBOX_SCHEMA_VERSION,
    PostgresParallelDispatchOutbox,
)
from .reasoning_parallel_projection import (
    PROJECTION_VERSION,
    ParallelBranchProjection,
    ParallelProjectionError,
    ParallelRunProjection,
    project_parallel_run,
)
from .workflow_router import (
    ActionRisk,
    ApprovalState,
    ExecutionLane,
    MechanicalState,
    SignalObservation,
    SignalState,
    TaskAtom,
    TaskIntent,
    WorkflowRouteCoordinator,
    WorkflowRouteError,
    WorkflowRouteRequest,
    WorkflowRoutingPolicy,
    WorkflowSignalAdapter,
)

from .workflow_route_ledger import (
    WorkflowRouteLedger,
    WorkflowRouteLedgerError,
)

from .workflow_route_sqlite_ledger import (
    SQLITE_ROUTE_SCHEMA_VERSION,
    SqliteWorkflowRouteLedger,
    workflow_route_stream_key,
)


__all__ = [
    "ALLOWED_TRANSITIONS",
    "ActionRisk",
    "ApprovalState",
    "ArtifactValidationError",
    "BudgetExceededError",
    "BudgetLedger",
    "BudgetLimits",
    "BudgetSnapshot",
    "BudgetUsage",
    "CandidateRequiredError",
    "ChainFactoryError",
    "ChainPlanDriftError",
    "ChainPlanSession",
    "ChainPlanStateError",
    "ChainStepOutcome",
    "DuplicateEventConflictError",
    "EventSchemaViolationError",
    "EventStore",
    "EventStorePersistenceError",
    "FeedbackAuthorizationError",
    "FeedbackBlockError",
    "IllegalTransitionError",
    "ExecutionLane",
    "JsonlEventStore",
    "MechanicalState",
    "NoProgressLimitError",
    "POSTGRES_EVENT_SCHEMA_VERSION",
    "POSTGRES_PARALLEL_OUTBOX_SCHEMA_VERSION",
    "ParallelBranchOutcome",
    "ParallelBranchProjection",
    "ParallelDispatchAcquisition",
    "ParallelDispatchClaimError",
    "ParallelDispatchCompletion",
    "ParallelDispatchConflictError",
    "ParallelDispatchCoordinator",
    "ParallelDispatchError",
    "ParallelDispatchOutbox",
    "ParallelFactoryError",
    "ParallelFinalizationOutcome",
    "ParallelDeadlineOutcome",
    "ParallelPathLease",
    "ParallelPathScheduler",
    "ParallelPlanDriftError",
    "ParallelPlanSession",
    "ParallelPlanStateError",
    "ParallelProjectionError",
    "ParallelRunProjection",
    "ParallelSynthesisOutcome",
    "ParallelWorkDispatch",
    "PROJECTION_VERSION",
    "PrivateReasoningCaptureError",
    "RUNTIME_SUPPORTED_STOP_TYPES",
    "ReasoningEngine",
    "ReasoningChainFactory",
    "ReasoningParallelFactory",
    "ReasoningEvent",
    "ReasoningRuntimeError",
    "ReplaySnapshot",
    "SignalObservation",
    "SignalState",
    "RiskLevel",
    "SQLITE_ROUTE_SCHEMA_VERSION",
    "SQLITE_EVENT_SCHEMA_VERSION",
    "SQLITE_PARALLEL_OUTBOX_SCHEMA_VERSION",
    "PostgresEventStore",
    "PostgresParallelDispatchOutbox",
    "SqliteEventStore",
    "SqliteParallelDispatchOutbox",
    "SqliteWorkflowRouteLedger",
    "RunSnapshot",
    "StepStartRecord",
    "StepRecord",
    "TaskAtom",
    "TaskIntent",
    "ToolAuthorizationError",
    "ValidationGateError",
    "ValidationRecord",
    "ValidationStatus",
    "ValidatorSpec",
    "WorkflowState",
    "WorkflowRouteCoordinator",
    "WorkflowRouteError",
    "WorkflowRouteLedger",
    "WorkflowRouteLedgerError",
    "WorkflowRouteRequest",
    "WorkflowRoutingPolicy",
    "WorkflowSignalAdapter",
    "artifact_fingerprint",
    "build_artifact",
    "candidate_binding_for",
    "candidate_fingerprint",
    "content_fingerprint",
    "evidence_sufficiency_failures",
    "project_parallel_run",
    "validate_artifact_hash",
    "validate_chain_blueprint",
    "validate_chain_plan",
    "validate_parallel_blueprint",
    "validate_parallel_plan",
    "validate_reasoning_contract",
    "validate_reasoning_event",
    "validate_reasoning_result",
    "validate_runtime_contract_capabilities",
    "validate_schema",
    "validate_workflow_route_envelope",
    "validate_workflow_route_revision",
    "workflow_route_stream_key",
]
