"""Executable reasoning reference runtime / 可执行推理参考运行时。

This package exposes a deterministic reference kernel and JSON Schema-backed
artifact guards for the reasoning execution protocol. It records externally
verifiable artifacts; it never asks for or persists private chain-of-thought.
/ 本包提供确定性推理协议参考内核和基于 JSON Schema 的制品闸门。它只记录
外部可核验产物，绝不请求或持久化私密思维过程。
"""

from .reasoning_artifacts import (
    ArtifactValidationError,
    artifact_fingerprint,
    build_artifact,
    evidence_sufficiency_failures,
    validate_artifact_hash,
    validate_reasoning_contract,
    validate_reasoning_event,
    validate_reasoning_result,
    validate_schema,
)

from .reasoning_runtime import (
    ALLOWED_TRANSITIONS,
    BudgetExceededError,
    BudgetLedger,
    BudgetLimits,
    BudgetSnapshot,
    BudgetUsage,
    CandidateRequiredError,
    DuplicateEventConflictError,
    EventSchemaViolationError,
    EventStore,
    EventStorePersistenceError,
    FeedbackAuthorizationError,
    FeedbackBlockError,
    IllegalTransitionError,
    JsonlEventStore,
    NoProgressLimitError,
    PrivateReasoningCaptureError,
    RUNTIME_SUPPORTED_STOP_TYPES,
    ReasoningEngine,
    ReasoningEvent,
    ReasoningRuntimeError,
    ReplaySnapshot,
    RiskLevel,
    RunSnapshot,
    StepStartRecord,
    StepRecord,
    ToolAuthorizationError,
    ValidationGateError,
    ValidationRecord,
    ValidationStatus,
    ValidatorSpec,
    WorkflowState,
    candidate_binding_for,
    candidate_fingerprint,
    content_fingerprint,
    validate_runtime_contract_capabilities,
)

from .reasoning_chain_factory import (
    ChainFactoryError,
    ChainPlanDriftError,
    ChainPlanSession,
    ChainPlanStateError,
    ChainStepOutcome,
    ReasoningChainFactory,
    validate_chain_blueprint,
    validate_chain_plan,
)

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ArtifactValidationError",
    "BudgetExceededError",
    "BudgetLedger",
    "BudgetLimits",
    "BudgetSnapshot",
    "BudgetUsage",
    "CandidateRequiredError",
    "ChainFactoryError",
    "ChainPlanDriftError",
    "ChainPlanSession",
    "ChainPlanStateError",
    "ChainStepOutcome",
    "DuplicateEventConflictError",
    "EventSchemaViolationError",
    "EventStore",
    "EventStorePersistenceError",
    "FeedbackAuthorizationError",
    "FeedbackBlockError",
    "IllegalTransitionError",
    "JsonlEventStore",
    "NoProgressLimitError",
    "PrivateReasoningCaptureError",
    "RUNTIME_SUPPORTED_STOP_TYPES",
    "ReasoningEngine",
    "ReasoningChainFactory",
    "ReasoningEvent",
    "ReasoningRuntimeError",
    "ReplaySnapshot",
    "RiskLevel",
    "RunSnapshot",
    "StepStartRecord",
    "StepRecord",
    "ToolAuthorizationError",
    "ValidationGateError",
    "ValidationRecord",
    "ValidationStatus",
    "ValidatorSpec",
    "WorkflowState",
    "artifact_fingerprint",
    "build_artifact",
    "candidate_binding_for",
    "candidate_fingerprint",
    "content_fingerprint",
    "evidence_sufficiency_failures",
    "validate_artifact_hash",
    "validate_chain_blueprint",
    "validate_chain_plan",
    "validate_reasoning_contract",
    "validate_reasoning_event",
    "validate_reasoning_result",
    "validate_runtime_contract_capabilities",
    "validate_schema",
]
